import HTTPLibrary

HOST = "httpbin.org"
HTTP_METHOD = "GET"
PATH = "/status/418"
QUERY_PARAMS = ""
HEADERS = []
BODY_DATA = None
VERBOSE = True

HTTPLibrary.sendHTTPRequest(HOST, HTTP_METHOD, PATH, QUERY_PARAMS, HEADERS, BODY_DATA, VERBOSE)